// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHqb7coWtEmTxSGHpSwyC78x__khj1mh8',
    appId: '1:933639983128:web:980a78ba99688e28cf336d',
    messagingSenderId: '933639983128',
    projectId: 'ebntz-app',
    authDomain: 'ebntz-app.firebaseapp.com',
    storageBucket: 'ebntz-app.appspot.com',
    measurementId: 'G-HN05T158Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkzvT1jJwrIMs7w5f8t65fXzDPTvtIdLc',
    appId: '1:933639983128:android:c853d3a5c54bd20acf336d',
    messagingSenderId: '933639983128',
    projectId: 'ebntz-app',
    storageBucket: 'ebntz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3L4OURQ2xJ3LYrTAp8isDGmXH5h1-zkg',
    appId: '1:933639983128:ios:9331e9863ea87464cf336d',
    messagingSenderId: '933639983128',
    projectId: 'ebntz-app',
    storageBucket: 'ebntz-app.appspot.com',
    iosClientId: '933639983128-8eru3lcskekde1jaamqmsssgh684tq8m.apps.googleusercontent.com',
    iosBundleId: 'com.sanfaina.ebntz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3L4OURQ2xJ3LYrTAp8isDGmXH5h1-zkg',
    appId: '1:933639983128:ios:9331e9863ea87464cf336d',
    messagingSenderId: '933639983128',
    projectId: 'ebntz-app',
    storageBucket: 'ebntz-app.appspot.com',
    iosClientId: '933639983128-8eru3lcskekde1jaamqmsssgh684tq8m.apps.googleusercontent.com',
    iosBundleId: 'com.sanfaina.ebntz',
  );
}
